version: "3.8"

services:
  hw2-service:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env
    depends_on:
      - hw2-postgres

  hw2-postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"

  hw2-nginx:
    image: nginx:1.19-alpine
    restart: always
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf
    ports:
      - "$BALANCER_PORT:80"
