version: "3.8"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - balancer

  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"

  balancer:
    image: nginx:1.19-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "$BALANCER_PORT:80"
