version: "3.8"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
    - $SERVICE_PORT:$SERVICE_PORT
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
